import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./content/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: "rgb(var(--brand-primary) / <alpha-value>)",
          "primary-hover": "rgb(var(--brand-primary-hover) / <alpha-value>)",
          gold: "rgb(var(--brand-gold) / <alpha-value>)",
          charcoal: "rgb(var(--brand-charcoal) / <alpha-value>)",
          "warm-white": "rgb(var(--brand-warm-white) / <alpha-value>)",
          parchment: "rgb(var(--brand-parchment) / <alpha-value>)",
        },
        primary: "#00261a",
        "primary-container": "#0f3d2e",
        "on-primary": "#ffffff",
        "on-primary-container": "#7ba894",
        "inverse-primary": "#a2d1bb",
        "primary-fixed": "#beedd7",
        "primary-fixed-dim": "#a2d1bb",
        "on-primary-fixed": "#002116",
        "on-primary-fixed-variant": "#234f3f",

        secondary: "#874f4b",
        "secondary-container": "#fdb4ae",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#794340",
        "secondary-fixed": "#ffdad7",
        "secondary-fixed-dim": "#fdb4ae",
        "on-secondary-fixed": "#360e0d",
        "on-secondary-fixed-variant": "#6b3835",

        tertiary: "#755b00",
        "tertiary-container": "#cea72c",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4f3d00",
        "tertiary-fixed": "#ffe08e",
        "tertiary-fixed-dim": "#ecc246",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#584400",

        background: "#fff9e9",
        surface: "#fff9e9",
        "surface-dim": "#dfdac9",
        "surface-bright": "#fff9e9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f3e2",
        "surface-container": "#f4eedd",
        "surface-container-high": "#eee8d7",
        "surface-container-highest": "#e8e2d1",
        "surface-variant": "#e8e2d1",
        "surface-tint": "#3b6756",
        "on-surface": "#1e1c12",
        "on-surface-variant": "#414944",
        "inverse-surface": "#333125",
        "inverse-on-surface": "#f6f0df",

        outline: "#717974",
        "outline-variant": "#c0c8c3",

        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "2rem",
        "container-max": "72rem",
      },
      fontFamily: {
        serif: ["var(--font-garamond)", "serif"],
        sans: ["var(--font-inter)", "sans-serif"],
        urdu: ["var(--font-urdu)", "serif"],
        quran: ["var(--font-amiri)", "serif"],
        "display-lg": ["var(--font-garamond)", "serif"],
        "display-md": ["var(--font-garamond)", "serif"],
        "headline-lg": ["var(--font-garamond)", "serif"],
        "headline-md": ["var(--font-garamond)", "serif"],
        "headline-sm": ["var(--font-garamond)", "serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-md-mobile": ["26px", { lineHeight: "34px", fontWeight: "600" }],
        "display-md": ["36px", { lineHeight: "44px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      letterSpacing: {
        editorial: "var(--tracking-editorial)",
      },
    },
  },
  plugins: [],
};

export default config;
